<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- LINKS -->
  <link name="neck_1">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.33878686"/>
      <!-- MASS/INERTIA TO DO -->
      <inertia ixx="0.0003718568" ixy="-9.42983e-05" ixz="-2.80644e-05" iyy="0.0001886879" iyz="-1.54534e-05" izz="0.0005023443"/>
    </inertial>
    <visual>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0 0.0"/>
      <geometry>
        <mesh filename="package://centauro_urdf/meshes/head-base_mesh.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0 0.0"/>
      <geometry>
        <mesh filename="package://centauro_urdf/meshes/simple/head-base_mesh.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <link name="velodyne_motor">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.33878686"/>
      <!-- MASS/INERTIA TO DO -->
      <inertia ixx="0.0003718568" ixy="-9.42983e-05" ixz="-2.80644e-05" iyy="0.0001886879" iyz="-1.54534e-05" izz="0.0005023443"/>
    </inertial>
    <visual>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0 0.0"/>
      <geometry>
        <mesh filename="package://centauro_urdf/meshes/lidar_mesh.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0 0.0"/>
      <geometry>
        <mesh filename="package://centauro_urdf/meshes/simple/lidar_mesh.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <link name="d435_head_motor">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.33878686"/>
      <!-- MASS/INERTIA TO DO -->
      <inertia ixx="0.0003718568" ixy="-9.42983e-05" ixz="-2.80644e-05" iyy="0.0001886879" iyz="-1.54534e-05" izz="0.0005023443"/>
    </inertial>
    <visual>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0 0.0"/>
      <geometry>
        <mesh filename="package://centauro_urdf/meshes/neck-pitch_mesh.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0.0 0.0 0.0" xyz="0.0 0 0.0"/>
      <geometry>
        <mesh filename="package://centauro_urdf/meshes/simple/neck-pitch_mesh.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <!--JOINTS -->
  <joint name="neck_base" type="fixed">
    <parent link="torso_2"/>
    <origin xyz="0.0030637045 0.0061607221 0.158" rpy="0 0 0"/>
    <child link="neck_1"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="velodyne_joint" type="revolute">
    <parent link="neck_1"/>
    <origin xyz="0.0822724 0 0.242" rpy="0 0 0"/>
    <child link="velodyne_motor"/>
    <axis xyz="0 -1 0"/>
    <limit effort="35" lower="-1.1" upper="1.1" velocity="5.7"/>
    <dynamics friction="10.0"/>
  </joint>

  <joint name="d435_head_joint" type="revolute">
    <parent link="neck_1"/>
    <origin xyz="0.06 0 0.1375" rpy="0 0 0"/>
    <child link="d435_head_motor"/>
    <axis xyz="0 -1 0"/>
    <limit effort="35" lower="-1.1" upper="1.1" velocity="5.7"/>
    <dynamics friction="10.0"/>
  </joint>

  <xacro:property name="d435_head_name" value="D435_head_camera" />
  <xacro:property name="d435_head_parent_name" value="d435_head_motor" />
  <xacro:property name="d435_head_origin">
    <origin xyz="0.03015 0 -0.0125" rpy="0 0 0"/>
  </xacro:property>

  <xacro:if value="${ADD_D435I_HEAD}">

    <xacro:include filename="$(find realsense_gazebo_description)/urdf/_d435i.urdf.xacro" />

    <xacro:sensor_d435i parent="${d435_head_parent_name}" 
        name="${d435_head_name}" 
        topics_ns="${d435_head_name}" 
        enable_pointCloud="true" 
        align_depth="true" 
        unite_imu_method="false" 
        visualize="false" 
        accel_fps="300" 
        gyro_fps="300" 
        depth_width="1280" 
        depth_height="720" 
        depth_fps="90" 
        infra_width="1280" 
        infra_height="720" 
        infra_fps="90" 
        color_width="1280" 
        color_height="720"
        color_fps="30">

        <xacro:insert_block name="d435_head_origin" />

    </xacro:sensor_d435i>
    
  </xacro:if>
  
  <xacro:unless value="${ADD_D435I_HEAD}">
      
    <!--  Copied from _d435.urdf.xacro    -->
    <xacro:property name="d435_cam_width" value="0.090"/>
    <xacro:property name="d435_cam_height" value="0.025"/>
    <xacro:property name="d435_cam_depth" value="0.02505"/>
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
    <xacro:property name="d435_cam_depth_py" value="0.0175"/>
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/> 
      
    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${d435_head_name}_joint" type="fixed">
      <xacro:insert_block name="d435_head_origin"/>
      <parent link="${d435_head_parent_name}"/>
      <child link="${d435_head_name}_bottom_screw_frame"/>
    </joint>
    <link name="${d435_head_name}_bottom_screw_frame"/>

    <joint name="${d435_head_name}_link_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="${d435_head_name}_bottom_screw_frame"/>
      <child link="${d435_head_name}_link"/>
    </joint>
    
    <link name="${d435_head_name}_link">
      <visual>
      <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <!-- <box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
          <mesh filename="package://centauro_urdf/meshes/realsense/d435.dae"/>
        </geometry>
        <material name="${d435_head_name}_aluminum"/>
      </visual>
      <collision>
        <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
        <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257"/>
      </inertial>
    </link>
    
  </xacro:unless>

  <xacro:if value="${USE_EUROBIN_HEAD}">
  <xacro:include filename="$(find centauro_urdf)/urdf/parts/zed_x_mini.urdf.xacro"/>
  <xacro:include filename="$(find centauro_urdf)/urdf/parts/zed_mini.urdf.xacro"/>
  <xacro:include filename="$(find realsense_gazebo_description)/urdf/_d435i.urdf.xacro"/>
  <xacro:include filename="$(find realsense_gazebo_description)/urdf/_d455.urdf.xacro"/>

    <xacro:if value="${USE_HEAD_ZED_MINI}">
        <xacro:zed_mini
            parent="neck_1"
            name="zed_mini_front1">

            <origin xyz="0.09 0.05 0.1375" rpy="-1.57 0 -0.5"/>

        </xacro:zed_mini>
        <xacro:zed_mini_gazebo
                name="zed_mini_front1"/>


        <xacro:zed_mini
            parent="neck_1"
            name="zed_mini_front2">

        <origin xyz="0.09 -0.05 0.1375" rpy="-1.57 0 0.5"/>

        </xacro:zed_mini>
        <xacro:zed_mini_gazebo
                name="zed_mini_front2"/>
    </xacro:if>

    <xacro:if value="${USE_HEAD_ZED_X_MINI}">
        <xacro:zed_x_mini
            parent="neck_1"
            name="zedx_front1">

            <origin xyz="0.09 0.05 0.1375" rpy="-1.57 0 -0.5"/>

        </xacro:zed_x_mini>
        <xacro:zed_x_mini_gazebo
                name="zedx_front1"/>


        <xacro:zed_x_mini
            parent="neck_1"
            name="zedx_front2">

        <origin xyz="0.09 -0.05 0.1375" rpy="-1.57 0 0.5"/>

        </xacro:zed_x_mini>
        <xacro:zed_x_mini_gazebo
                name="zedx_front2"/>
      </xacro:if>

    <xacro:if value="${USE_HEAD_D435}">
        <xacro:sensor_d435i parent="neck_1"
            name="d435_head_1"
            topics_ns="d435_head_1"
            enable_pointCloud="true"
            align_depth="true"
            unite_imu_method="false"
            visualize="false"
            accel_fps="300"
            gyro_fps="300"
            depth_width="1280"
            depth_height="720"
            depth_fps="90"
            infra_width="1280"
            infra_height="720"
            infra_fps="90"
            color_width="1280"
            color_height="720"
            color_fps="30">

            <origin xyz="0.09 0.05 0.1375" rpy="-1.57 0 -0.5"/>
        </xacro:sensor_d435i>

        <xacro:sensor_d435i parent="neck_1"
            name="d435_head_2"
            topics_ns="d435_head_2"
            enable_pointCloud="true"
            align_depth="true"
            unite_imu_method="false"
            visualize="false"
            accel_fps="300"
            gyro_fps="300"
            depth_width="1280"
            depth_height="720"
            depth_fps="90"
            infra_width="1280"
            infra_height="720"
            infra_fps="90"
            color_width="1280"
            color_height="720"
            color_fps="30">

            <origin xyz="0.09 -0.05 0.1375" rpy="-1.57 0 0.5"/>
        </xacro:sensor_d435i>
    </xacro:if>

    <xacro:if value="${USE_HEAD_D455}">
        <xacro:sensor_d455 parent="neck_1"
            name="d455_head_1"
            topics_ns="d455_head_1"
            enable_pointCloud="true"
            align_depth="true"
            unite_imu_method="false"
            visualize="false"
            accel_fps="300"
            gyro_fps="300"
            depth_width="1280"
            depth_height="720"
            depth_fps="90"
            infra_width="1280"
            infra_height="720"
            infra_fps="90"
            color_width="1280"
            color_height="720"
            color_fps="30">

            <origin xyz="0.08 0.065 0.1375" rpy="-1.57 0 -0.52"/>
        </xacro:sensor_d455>

        <xacro:sensor_d455 parent="neck_1"
            name="d455_head_2"
            topics_ns="d455_head_2"
            enable_pointCloud="true"
            align_depth="true"
            unite_imu_method="false"
            visualize="false"
            accel_fps="300"
            gyro_fps="300"
            depth_width="1280"
            depth_height="720"
            depth_fps="90"
            infra_width="1280"
            infra_height="720"
            infra_fps="90"
            color_width="1280"
            color_height="720"
            color_fps="30">

            <origin xyz="0.08 -0.065 0.1375" rpy="-1.57 0 0.52"/>
        </xacro:sensor_d455>
    </xacro:if>
  </xacro:if>

  <xacro:if value="${ADD_VELODYNE}">
    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
    <xacro:VLP-16 parent="velodyne_motor" name="velodyne_calib" topic="/velodyne_points" hz="10" samples="440">
        <origin xyz="-0.01 0.02 0.06" rpy="0.025 0.019 0" />
    </xacro:VLP-16>
  </xacro:if>

</robot>
